expand: support ~ on Windows without $HOME
And add a test, which failed under Wine:

	--- FAIL: TestFields (0.00s)
	    --- FAIL: TestFields/10 (0.00s)
		expand_test.go:122:
		    want: ["/my/home"]
		    got:  [""]

While at it, rewrite interp.New's HOME fallback to use os.UserHomeDir,
since that doesn't rely on cgo.

Fixes #410.