Revert "interp: re-enable process substitution tests on Mac"
Reason for revert: CI ran into failures again.

	--- FAIL: TestRunnerRun/#919 (0.01s)
		interp_test.go:3229: wrong output in "cat <(cat <(echo nested))":
			want: "nested\n"
			got:  "open /var/[...]/sh-interp-4767e74e48b9ec1c: no such file or directory"

This reverts commit 676b655edf7dec31f9159f51d11af48f707aab4d.

Reopens #576.