interp: make the new background shell tests more resilient
`echo $n` seems to write each argument first, then a newline separately,
which sometimes caused the writes to be interleaved between subshells
running concurrently:

    --- FAIL: TestRunnerRun/#456 (0.00s)
        interp_test.go:3662: wrong output in "{ for n in {0..9}; do { echo $n; } & done; wait; } | sort":
            want: "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n"
            got:  "\n0\n13\n2\n4\n5\n6\n7\n8\n9\n"

Fix that by adding a newline at the end of the string instead.