interp: standardize locale settings
i was getting some test failures:
```
  --- FAIL: TestParseErrBashConfirm (0.00s)
  --- FAIL: TestParseErrBashConfirm/#204 (0.03s)
      parser_test.go:331: Expected error in "bash" of "echo \"`)`\"", found none
  --- FAIL: TestParseErrBashConfirm/#289 (0.03s)
      parser_test.go:331: Expected error in "bash" of "echo $((a[]))", found none
```

a bit misleading because bash really did error on those cases, this is
what's written in the stderr:
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF8): No such file or directory
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `)'
```

but since our code ignores any error from bash that contains `: warning: `, the
error wasn't properly set and the test assumed no error was encountered

fixed that by changing the locale env vars to `en_US.UTF-8` which should
be portable across platforms

while at it, also add `t.Helper` on `confirmParse` so that tests
actually prints the failing line